-- SEED: 50 Government Schemes
-- Run this in Supabase SQL Editor to populate the database.

INSERT INTO schemes (name, ministry, description, benefits, eligibility_criteria, benefit_amount, status)
VALUES
('Solar Rooftop Subsidy', 'Ministry of New and Renewable Energy', 'Subsidy for installing solar panels on residential rooftops.', ARRAY['40% subsidy for up to 3kW', '20% subsidy for 3kW-10kW'], '{"residence_type": ["urban", "rural"]}', 14580, 'active'),
('PM Gram Sadak Yojana', 'Ministry of Rural Development', 'Connecting unconnected habitations with all-weather roads.', ARRAY['Better connectivity', 'Economic growth'], '{"residence_type": ["rural"]}', NULL, 'active'),
('Ayushman Bharat', 'Ministry of Health', 'Health insurance coverage for secondary and tertiary care hospitalization.', ARRAY['₹5 Lakhs per family per year', 'Cashless treatment'], '{"max_income": 250000}', 500000, 'active'),
('Skill India Mission', 'Ministry of Skill Development', 'Training and certification for youth to improve employability.', ARRAY['Free training', 'Placement assistance'], '{"min_age": 18, "max_age": 35}', NULL, 'active'),
('Digital India Internship', 'Ministry of Electronics', 'Internship opportunities for students in e-Governance projects.', ARRAY['Stipend ₹10,000/month', 'Certificate'], '{"allowed_occupations": ["student"]}', 10000, 'active'),
('Atal Pension Yojana', 'Ministry of Finance', 'Pension scheme for unorganized sector workers.', ARRAY['Guaranteed pension', 'Government contribution'], '{"min_age": 18, "max_age": 40}', NULL, 'active'),
('Pradhan Mantri Mudra Yojana', 'Ministry of Finance', 'Loans for small and micro enterprises.', ARRAY['Loans up to ₹10 Lakhs', 'No collateral'], '{"occupation": "self_employed"}', 1000000, 'active'),
('Stand Up India', 'Ministry of Finance', 'Loans for SC/ST and women entrepreneurs.', ARRAY['₹10 Lakhs to ₹1 Crore loan'], '{"gender": ["female"], "category": ["SC", "ST"]}', 10000000, 'active'),
('Fame India Phase II', 'Ministry of Heavy Industries', 'Subsidy for electric vehicle purchase.', ARRAY['Up to ₹1.5 Lakhs based on battery capacity'], '{"vehicle_type": "electric"}', 150000, 'active'),
('Ujjwala Yojana', 'Ministry of Petroleum', 'Free LPG connections to women of BPL households.', ARRAY['Free gas connection', 'Subsidy on cylinders'], '{"gender": ["female"], "income_category": "BPL"}', 1600, 'active'),
('Sukanya Samriddhi Yojana', 'Ministry of Finance', 'Savings scheme for the girl child.', ARRAY['High interest rate', 'Tax benefits'], '{"gender": ["female"], "max_age": 10}', NULL, 'active'),
('PM Fasal Bima Yojana', 'Ministry of Agriculture', 'Crop insurance scheme for farmers.', ARRAY['Insurance against crop loss', 'Low premium'], '{"occupation": "farmer"}', NULL, 'active'),
('Green Energy Corridor', 'Ministry of New and Renewable Energy', 'Transmission infrastructure for renewable energy.', ARRAY['Grid stability', 'Clean energy integration'], '{}', NULL, 'active'),
('National Health Mission', 'Ministry of Health', 'Universal access to equitable, affordable & quality health care services.', ARRAY['Free medicines', 'Maternal care'], '{}', NULL, 'active'),
('Mid-Day Meal Scheme', 'Ministry of Education', 'Free lunch for children in primary and upper primary schools.', ARRAY['Improve nutrition', 'Increase attendance'], '{"occupation": "student", "age_group": "6-14"}', NULL, 'active'),
('Beti Bachao Beti Padhao', 'Ministry of Women and Child Development', 'Campaign to improve child sex ratio and educate girl child.', ARRAY['Awareness', 'Educational incentives'], '{"gender": ["female"]}', NULL, 'active'),
('Smart Cities Mission', 'Ministry of Housing and Urban Affairs', 'Promote cities that provide core infrastructure and decent quality of life.', ARRAY['Better infrastructure', 'Smart solutions'], '{"residence_type": ["urban"]}', NULL, 'active'),
('AMRUT', 'Ministry of Housing and Urban Affairs', 'Atal Mission for Rejuvenation and Urban Transformation.', ARRAY['Water supply', 'Sewerage'], '{"residence_type": ["urban"]}', NULL, 'active'),
('Swachh Bharat Mission', 'Ministry of Jal Shakti', 'Clean consolidation and sanitation.', ARRAY['IHHL incentive ₹12,000', 'Community toilets'], '{}', 12000, 'active'),
('Namami Gange', 'Ministry of Jal Shakti', 'Conservation and rejuvenation of National River Ganga.', ARRAY['Pollution abatement', 'Riverfront development'], '{}', NULL, 'active'),
('PM Jan Dhan Yojana', 'Ministry of Finance', 'Financial inclusion for all households.', ARRAY['Zero balance account', 'RuPay debit card'], '{}', NULL, 'active'),
('Gold Monetization Scheme', 'Ministry of Finance', 'Mobilize gold held by households and institutions.', ARRAY['Interest on gold', 'Tax exemption'], '{}', NULL, 'active'),
('Sovereign Gold Bond', 'Ministry of Finance', 'Substitute for holding physical gold.', ARRAY['2.5% interest', 'Capital gains tax exemption'], '{}', NULL, 'active'),
('PM Jeevan Jyoti Bima Yojana', 'Ministry of Finance', 'Life insurance scheme.', ARRAY['₹2 Lakhs life cover', 'Premium ₹436/year'], '{"min_age": 18, "max_age": 50}', 200000, 'active'),
('PM Suraksha Bima Yojana', 'Ministry of Finance', 'Accidental death and disability insurance.', ARRAY['₹2 Lakhs cover', 'Premium ₹20/year'], '{"min_age": 18, "max_age": 70}', 200000, 'active'),
('Rashtriya Gokul Mission', 'Ministry of Fisheries, Animal Husbandry', 'Development and conservation of indigenous bovine breeds.', ARRAY['Breed improvement', 'Milk production'], '{"occupation": "farmer"}', NULL, 'active'),
('Blue Revolution', 'Ministry of Fisheries', 'Integrated development and management of fisheries.', ARRAY['Financial assistance for nets/boats'], '{"occupation": "fisherman"}', NULL, 'active'),
('PM Matru Vandana Yojana', 'Ministry of Women and Child Development', 'Maternity benefit program.', ARRAY['₹5000 cash incentive'], '{"gender": ["female"], "condition": "pregnant"}', 5000, 'active'),
('Poshan Abhiyaan', 'Ministry of Women and Child Development', 'Holistic nourishment for children, pregnant women.', ARRAY['Nutritional support', 'Health monitoring'], '{}', NULL, 'active'),
('Khelo India', 'Ministry of Youth Affairs', 'Revive sports culture in India.', ARRAY['Scholarship ₹5 Lakhs/year', 'Training'], '{"occupation": "student", "interest": "sports"}', 500000, 'active'),
('Fit India Movement', 'Ministry of Youth Affairs', 'Encourage people to remain healthy and fit.', ARRAY['Health awareness'], '{}', NULL, 'active'),
('Make in India', 'Ministry of Commerce', 'Facilitate investment and foster innovation.', ARRAY['Ease of doing business', 'Incentives'], '{"occupation": "business"}', NULL, 'active'),
('Production Linked Incentive', 'Ministry of Commerce', 'Boost domestic manufacturing.', ARRAY['4-6% incentive on incremental sales'], '{"sector": "manufacturing"}', NULL, 'active'),
('UDAN Scheme', 'Ministry of Civil Aviation', 'Regional connectivity scheme.', ARRAY['Subsidized airfare'], '{}', NULL, 'active'),
('Sagar Mala', 'Ministry of Ports', 'Port-led prosperity.', ARRAY['Port modernization', 'Connectivity'], '{}', NULL, 'active'),
('Bharatmala Pariyojana', 'Ministry of Road Transport', 'Road development project.', ARRAY['Economic corridors', 'Inter-corridors'], '{}', NULL, 'active'),
('Dedication Freight Corridor', 'Ministry of Railways', 'High speed freight movement.', ARRAY['Reduced logistics cost'], '{}', NULL, 'active'),
('Jal Jeevan Mission', 'Ministry of Jal Shakti', 'Piped water supply to all rural households.', ARRAY['FHTC to every household'], '{"residence_type": ["rural"]}', NULL, 'active'),
('Gramin Bhandaran Yojana', 'Ministry of Agriculture', 'Creation of scientific storage capacity in rural areas.', ARRAY['Subsidy for godown construction'], '{"residence_type": ["rural"]}', NULL, 'active'),
('National Bamboo Mission', 'Ministry of Agriculture', 'Promote growth of bamboo sector.', ARRAY['Subsidy on plantation'], '{"occupation": "farmer"}', NULL, 'active'),
('Soil Health Card Scheme', 'Ministry of Agriculture', 'Assess soil health and recommend nutrients.', ARRAY['Soil testing', 'Fertilizer recommendations'], '{"occupation": "farmer"}', NULL, 'active'),
('Paramparagat Krishi Vikas Yojana', 'Ministry of Agriculture', 'Promote organic farming.', ARRAY['₹50,000 per hectare'], '{"occupation": "farmer"}', 50000, 'active'),
('Mission for Integrated Development of Horticulture', 'Ministry of Agriculture', 'Holistic growth of horticulture sector.', ARRAY['Subsidy for polyhouses', 'Cold storage'], '{"occupation": "farmer"}', NULL, 'active'),
('e-NAM', 'Ministry of Agriculture', 'National Agriculture Market.', ARRAY['Better price discovery', 'Unified market'], '{"occupation": "farmer"}', NULL, 'active'),
('Pradhan Mantri Krishi Sinchayee Yojana', 'Ministry of Agriculture', 'Water efficiency in agriculture.', ARRAY['Subsidy for drip irrigation'], '{"occupation": "farmer"}', NULL, 'active'),
('National Food Security Mission', 'Ministry of Agriculture', 'Increase production of rice, wheat, pulses.', ARRAY['Seed distribution', 'Machinery subsidy'], '{"occupation": "farmer"}', NULL, 'active'),
('National Livestock Mission', 'Ministry of Fisheries', 'Sustainable development of livestock sector.', ARRAY['Subsidy for fodder', 'Risk management'], '{"occupation": "farmer"}', NULL, 'active'),
('PM Matsya Sampada Yojana', 'Ministry of Fisheries', 'Ecologically healthy and economically viable fisheries.', ARRAY['Support for new ponds', 'Inputs'], '{"occupation": "fisherman"}', NULL, 'active'),
('Vigyan Jyoti', 'Ministry of Science and Technology', 'Encourage girls in STEM.', ARRAY['Camps', 'Mentorship'], '{"gender": ["female"], "occupation": "student"}', NULL, 'active'),
('Inspire Scholarship', 'Ministry of Science and Technology', 'Attract talent to science.', ARRAY['₹80,000 per year'], '{"occupation": "student", "stream": "science"}', 80000, 'active');
